-- Sprint 2 — HU-03 (registro de nave) y HU-04 (disponibilidad de nombre)
-- Incluye las tablas base de HU-01/HU-02 (usuarios) y las de propietario /
-- agente residente, porque HU-03 exige asociar la nave a ambos.

-- ---------------------------------------------------------------
-- HU-01 / HU-02 — usuarios del sistema
-- ---------------------------------------------------------------
CREATE TABLE usuario (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correo          VARCHAR(120) NOT NULL,
    password_hash   VARCHAR(100) NOT NULL,
    nombre_completo VARCHAR(150) NOT NULL,
    rol             VARCHAR(30)  NOT NULL,
    activo          BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_creacion  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_usuario_correo UNIQUE (correo)
);

-- ---------------------------------------------------------------
-- Partes de la nave (necesarias para HU-03)
-- ---------------------------------------------------------------
CREATE TABLE propietario (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(150) NOT NULL,
    identificacion  VARCHAR(50)  NOT NULL,
    nacionalidad    VARCHAR(80)  NOT NULL,
    CONSTRAINT uk_propietario_identificacion UNIQUE (identificacion)
);

CREATE TABLE agente_residente (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(150) NOT NULL,
    idoneidad       VARCHAR(50)  NOT NULL,
    CONSTRAINT uk_agente_idoneidad UNIQUE (idoneidad)
);

-- ---------------------------------------------------------------
-- HU-03 / HU-04 — nave comercial
-- nombre_normalizado guarda el nombre en mayusculas y sin espacios
-- sobrantes; sobre esa columna va el UNIQUE que hace cumplir HU-04
-- incluso si alguien salta la pantalla y pega directo al endpoint.
-- ---------------------------------------------------------------
CREATE TABLE nave (
    id                    BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre                VARCHAR(120) NOT NULL,
    nombre_normalizado    VARCHAR(120) NOT NULL,
    tipo                  VARCHAR(30)  NOT NULL,
    servicio              VARCHAR(30)  NOT NULL,

    -- tonelaje
    tonelaje_bruto        NUMERIC(12,2) NOT NULL,
    tonelaje_neto         NUMERIC(12,2) NOT NULL,

    -- dimensiones (metros)
    eslora                NUMERIC(8,2)  NOT NULL,
    manga                 NUMERIC(8,2)  NOT NULL,
    puntal                NUMERIC(8,2)  NOT NULL,

    -- construccion
    anio_construccion     INTEGER      NOT NULL,
    lugar_construccion    VARCHAR(120) NOT NULL,
    material_casco        VARCHAR(60)  NOT NULL,

    -- propulsion
    tipo_propulsion       VARCHAR(60)  NOT NULL,
    potencia_kw           NUMERIC(10,2) NOT NULL,

    estado                VARCHAR(30)  NOT NULL DEFAULT 'REGISTRADA',
    fecha_registro        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    propietario_id        BIGINT       NOT NULL,
    agente_residente_id   BIGINT       NOT NULL,
    registrado_por_id     BIGINT,

    CONSTRAINT uk_nave_nombre_normalizado UNIQUE (nombre_normalizado),
    CONSTRAINT fk_nave_propietario  FOREIGN KEY (propietario_id)      REFERENCES propietario (id),
    CONSTRAINT fk_nave_agente       FOREIGN KEY (agente_residente_id) REFERENCES agente_residente (id),
    CONSTRAINT fk_nave_usuario      FOREIGN KEY (registrado_por_id)   REFERENCES usuario (id)
);

CREATE INDEX idx_nave_nombre_normalizado ON nave (nombre_normalizado);
