-- =====================================================================
-- Sprint 3 — HU-05 (registro de propietario) y HU-06 (designacion de
-- agente residente).
--
-- Esta migracion reestructura el modelo del Sprint 2:
--
--   Antes:  nave.propietario_id      NOT NULL  (una nave, un propietario)
--           nave.agente_residente_id NOT NULL  (elegido de un catalogo)
--
--   Ahora:  nave_propietario     (una nave, uno o mas propietarios)
--           agentes_residentes   (una designacion por nave, con historia)
--
-- El cambio es necesario porque HU-06 exige que se pueda verificar si una
-- nave tiene propietario antes de designarle agente. Con el propietario
-- obligatorio en el registro de la nave, esa verificacion nunca falla.
-- =====================================================================


-- ---------------------------------------------------------------------
-- 0. Remediacion del hallazgo SEC-02 del informe de seguridad
--    El fuzzing del Sprint 2 creo una nave con nombre "admin'--".
-- ---------------------------------------------------------------------
DELETE FROM nave WHERE nombre = 'admin''--';


-- ---------------------------------------------------------------------
-- 1. Soltar las llaves foraneas que atan la nave a un unico propietario
--    y a un unico agente. Las columnas se eliminan al final, despues de
--    migrar los datos que contienen.
-- ---------------------------------------------------------------------
ALTER TABLE nave DROP CONSTRAINT fk_nave_propietario;
ALTER TABLE nave DROP CONSTRAINT fk_nave_agente;


-- ---------------------------------------------------------------------
-- 2. PROPIETARIOS
--    Se renombra la tabla del Sprint 2 y se extiende con los campos que
--    pide HU-05. La identificacion pasa a ser opcional: HU-05 no la
--    exige y una persona natural extranjera puede no tener RUC.
-- ---------------------------------------------------------------------
ALTER TABLE propietario RENAME TO propietarios;
ALTER TABLE propietarios RENAME CONSTRAINT uk_propietario_identificacion
                                TO uk_propietarios_identificacion;

ALTER TABLE propietarios
    ADD COLUMN tipo              VARCHAR(20),
    ADD COLUMN domicilio         VARCHAR(250),
    ADD COLUMN pais_constitucion VARCHAR(80),
    ADD COLUMN fecha_registro    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN registrado_por_id BIGINT;

-- Los dos propietarios de demo del Sprint 2 son sociedades.
UPDATE propietarios
   SET tipo              = 'JURIDICA',
       domicilio         = 'Pendiente de actualizar',
       pais_constitucion = nacionalidad
 WHERE tipo IS NULL;

ALTER TABLE propietarios ALTER COLUMN tipo           SET NOT NULL;
ALTER TABLE propietarios ALTER COLUMN domicilio      SET NOT NULL;
ALTER TABLE propietarios ALTER COLUMN identificacion DROP NOT NULL;

ALTER TABLE propietarios
    ADD CONSTRAINT ck_propietarios_tipo
        CHECK (tipo IN ('NATURAL', 'JURIDICA')),
    -- Regla de HU-05: si es persona juridica, el pais de constitucion
    -- es obligatorio. La base lo exige, no solo el backend.
    ADD CONSTRAINT ck_propietarios_pais_constitucion
        CHECK (tipo <> 'JURIDICA' OR pais_constitucion IS NOT NULL),
    ADD CONSTRAINT fk_propietarios_usuario
        FOREIGN KEY (registrado_por_id) REFERENCES usuario (id);


-- ---------------------------------------------------------------------
-- 3. NAVE_PROPIETARIO
--    Relacion muchos a muchos con cuota de participacion. La suma de
--    porcentajes por nave la valida el backend; aqui se acota cada fila.
-- ---------------------------------------------------------------------
CREATE TABLE nave_propietario (
    id                BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nave_id           BIGINT        NOT NULL,
    propietario_id    BIGINT        NOT NULL,
    porcentaje        NUMERIC(5,2)  NOT NULL DEFAULT 100.00,
    fecha_vinculacion TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_nave_propietario UNIQUE (nave_id, propietario_id),
    CONSTRAINT ck_nave_propietario_porcentaje
        CHECK (porcentaje > 0 AND porcentaje <= 100),
    CONSTRAINT fk_np_nave
        FOREIGN KEY (nave_id) REFERENCES nave (id) ON DELETE CASCADE,
    CONSTRAINT fk_np_propietario
        FOREIGN KEY (propietario_id) REFERENCES propietarios (id)
);

CREATE INDEX idx_nave_propietario_nave ON nave_propietario (nave_id);

-- Migrar los vinculos que ya existian en la columna de la nave.
INSERT INTO nave_propietario (nave_id, propietario_id, porcentaje)
SELECT id, propietario_id, 100.00
  FROM nave
 WHERE propietario_id IS NOT NULL;


-- ---------------------------------------------------------------------
-- 4. AGENTES_RESIDENTES
--    Deja de ser un catalogo compartido y pasa a ser una designacion por
--    nave. Guarda tambien la referencia del poder que pide HU-06; el
--    archivo en si se adjunta en HU-07.
-- ---------------------------------------------------------------------
ALTER TABLE agente_residente RENAME TO agentes_residentes;
ALTER TABLE agentes_residentes DROP CONSTRAINT uk_agente_idoneidad;

ALTER TABLE agentes_residentes
    ADD COLUMN nave_id           BIGINT,
    ADD COLUMN telefono          VARCHAR(40),
    ADD COLUMN correo            VARCHAR(120),
    ADD COLUMN poder_numero      VARCHAR(60),
    ADD COLUMN poder_fecha       DATE,
    ADD COLUMN poder_lugar       VARCHAR(150),
    ADD COLUMN vigente           BOOLEAN   NOT NULL DEFAULT TRUE,
    ADD COLUMN fecha_designacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN designado_por_id  BIGINT;

-- La idoneidad solo aplica a un abogado individual, no a una firma.
ALTER TABLE agentes_residentes ALTER COLUMN idoneidad DROP NOT NULL;

-- Convertir cada asignacion existente en una designacion propia de su nave.
INSERT INTO agentes_residentes (nombre, idoneidad, nave_id, vigente)
SELECT a.nombre, a.idoneidad, n.id, TRUE
  FROM nave n
  JOIN agentes_residentes a ON a.id = n.agente_residente_id
 WHERE n.agente_residente_id IS NOT NULL;

-- Descartar las filas de catalogo que quedaron sin nave.
DELETE FROM agentes_residentes WHERE nave_id IS NULL;

ALTER TABLE agentes_residentes ALTER COLUMN nave_id SET NOT NULL;

ALTER TABLE agentes_residentes
    ADD CONSTRAINT fk_agentes_nave
        FOREIGN KEY (nave_id) REFERENCES nave (id) ON DELETE CASCADE,
    ADD CONSTRAINT fk_agentes_usuario
        FOREIGN KEY (designado_por_id) REFERENCES usuario (id);

-- Nota: no se pone UNIQUE sobre la idoneidad. El mismo abogado puede ser
-- agente de muchas naves, y una nave puede volver a designar a un agente
-- que ya tuvo antes, con lo que quedarian dos filas historicas iguales.

-- Regla central de HU-06: una sola designacion vigente por nave.
-- El indice parcial deja convivir las designaciones historicas.
CREATE UNIQUE INDEX uk_agente_vigente_por_nave
    ON agentes_residentes (nave_id) WHERE vigente;


-- ---------------------------------------------------------------------
-- 5. Quitar de la nave las columnas que ya migraron
-- ---------------------------------------------------------------------
ALTER TABLE nave DROP COLUMN propietario_id;
ALTER TABLE nave DROP COLUMN agente_residente_id;


-- ---------------------------------------------------------------------
-- 6. Control de acceso de HU-05
--    "Solo sobre naves que el mismo registro" exige saber quien registro
--    cada nave. La columna existia pero admitia nulos.
-- ---------------------------------------------------------------------
UPDATE nave
   SET registrado_por_id = (SELECT id FROM usuario WHERE correo = 'agente@navesitas.pa')
 WHERE registrado_por_id IS NULL;

ALTER TABLE nave ALTER COLUMN registrado_por_id SET NOT NULL;
