-- =====================================================================
-- Sprint 4
--   1. HU-07 / HU-08: tabla DOCUMENTOS.
--   2. Observacion de la profesora: hora de creacion de la nave con zona.
--   3. Observacion de la profesora: el rol del usuario, explicito y acotado.
--   4. Observacion de la profesora: validacion del correo al registrarse.
--
-- El arreglo de MIG-01 no esta aqui: tiene que correr antes de la V4.
-- Ver V3_1__propietario_de_naves_huerfanas.sql.
-- =====================================================================


-- ---------------------------------------------------------------------
-- 1. DOCUMENTOS
--
-- El archivo vive en disco (carpeta almacen/, fuera de static/, que no
-- se sirve por URL); aqui va la ruta relativa y los datos de control.
-- La ruta la genera el servidor ({naveId}/{uuid}.pdf); nombre_archivo es
-- el nombre que mando el cliente, ya limpio, y solo se usa para mostrar
-- y para el nombre de la descarga.
-- ---------------------------------------------------------------------
CREATE TABLE documentos (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nave_id         BIGINT       NOT NULL,
    tipo            VARCHAR(30)  NOT NULL,
    nombre_archivo  VARCHAR(255) NOT NULL,
    ruta            VARCHAR(255) NOT NULL,
    hash_sha256     VARCHAR(64)  NOT NULL,
    tamano_bytes    BIGINT       NOT NULL,
    version         INTEGER      NOT NULL,
    vigente         BOOLEAN      NOT NULL DEFAULT TRUE,
    estado          VARCHAR(20)  NOT NULL DEFAULT 'PENDIENTE',
    creado_en       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    creado_por      BIGINT       NOT NULL,

    CONSTRAINT fk_documentos_nave    FOREIGN KEY (nave_id)    REFERENCES nave (id) ON DELETE CASCADE,
    CONSTRAINT fk_documentos_usuario FOREIGN KEY (creado_por) REFERENCES usuario (id),
    CONSTRAINT uk_documentos_ruta    UNIQUE (ruta),
    CONSTRAINT uk_documentos_version UNIQUE (nave_id, tipo, version),

    -- Lista cerrada de HU-07, criterio 1.
    CONSTRAINT ck_documentos_tipo
        CHECK (tipo IN ('CERTIFICADO_PROPIEDAD', 'PODER_NOTARIAL', 'ITC', 'SMC')),
    CONSTRAINT ck_documentos_estado
        CHECK (estado IN ('PENDIENTE', 'APROBADO', 'OBSERVADO')),
    -- Criterio 4: el limite tambien lo sostiene la base.
    CONSTRAINT ck_documentos_tamano
        CHECK (tamano_bytes > 0 AND tamano_bytes <= 10485760),
    CONSTRAINT ck_documentos_version CHECK (version >= 1),
    CONSTRAINT ck_documentos_hash    CHECK (hash_sha256 ~ '^[0-9a-f]{64}$')
);

-- Criterio 7 de HU-07: una sola version vigente por tipo y nave. Las
-- anteriores quedan con vigente = false, igual que el historial de
-- agentes residentes del Sprint 3.
CREATE UNIQUE INDEX uk_documentos_vigente ON documentos (nave_id, tipo) WHERE vigente;

-- La consulta de HU-08 filtra siempre por nave, y casi siempre por vigente.
CREATE INDEX idx_documentos_nave ON documentos (nave_id, vigente, tipo);


-- ---------------------------------------------------------------------
-- 2. Hora de creacion de la nave
--
-- fecha_registro es TIMESTAMP sin zona: guarda la hora del reloj del
-- servidor sin decir de que zona es. Se reemplaza por creado_en con
-- zona. Los registros existentes se interpretan en hora de Panama, que es
-- donde corrio el servidor en todos los sprints.
-- ---------------------------------------------------------------------
ALTER TABLE nave ADD COLUMN creado_en TIMESTAMPTZ NOT NULL DEFAULT now();
UPDATE nave SET creado_en = fecha_registro AT TIME ZONE 'America/Panama';
ALTER TABLE nave DROP COLUMN fecha_registro;


-- ---------------------------------------------------------------------
-- 3. Rol del usuario
--
-- La columna rol existia, pero aceptaba cualquier texto y no habia forma
-- de marcar a un auditor. Se agrega AUDITOR y se acota la lista.
-- ---------------------------------------------------------------------
ALTER TABLE usuario
    ADD CONSTRAINT ck_usuario_rol
        CHECK (rol IN ('AGENTE_NAVIERO', 'FUNCIONARIO_DGMM', 'AUDITOR', 'ADMINISTRADOR'));

-- Usuario de demostracion con el rol nuevo. Misma contrasena que los
-- demas: Navesitas2026*
INSERT INTO usuario (correo, password_hash, nombre_completo, rol)
SELECT 'auditor@navesitas.pa',
       '$2a$10$fsjHC3ZBRgiKDO8cUEaV5udNHU20wq5NUGjBy8iiIj6dHT4ZteW3.',
       'Auditor de Prueba', 'AUDITOR'
 WHERE NOT EXISTS (SELECT 1 FROM usuario WHERE correo = 'auditor@navesitas.pa');


-- ---------------------------------------------------------------------
-- 4. Validacion del correo
--
-- La cuenta no inicia sesion hasta confirmar el correo. El token se
-- guarda como hash SHA-256, no en claro: si alguien lee la tabla no
-- puede usar los enlaces pendientes. Expira a las 24 horas.
-- ---------------------------------------------------------------------
ALTER TABLE usuario
    ADD COLUMN correo_validado  BOOLEAN     NOT NULL DEFAULT FALSE,
    ADD COLUMN token_validacion VARCHAR(64),
    ADD COLUMN token_expira_en  TIMESTAMPTZ;

-- Las cuentas que ya existian (incluidos los usuarios de demo) se dan por
-- validadas: se crearon antes de que existiera la regla, y si no, nadie
-- podria entrar despues de migrar.
UPDATE usuario SET correo_validado = TRUE;

ALTER TABLE usuario
    ADD CONSTRAINT uk_usuario_token UNIQUE (token_validacion),
    -- Un token pendiente siempre lleva su vencimiento.
    ADD CONSTRAINT ck_usuario_token_expira
        CHECK (token_validacion IS NULL OR token_expira_en IS NOT NULL);
